// <auto-generated />
using EnergyUtilityApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnergyUtilityApi.Migrations
{
    [DbContext(typeof(EnergyUtilityDbContext))]
    partial class EnergyUtilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnergyUtilityApi.AllPostcodeDno", b =>
                {
                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .HasColumnName("postcode")
                        .IsFixedLength();

                    b.Property<int?>("DnoId")
                        .HasColumnType("integer")
                        .HasColumnName("dno_id");

                    b.HasKey("Postcode")
                        .HasName("postcodes_with_dno_pkey");

                    b.ToTable("all_postcode_dnos", (string)null);
                });

            modelBuilder.Entity("EnergyUtilityApi.Dno", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Operator")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("operator");

                    b.Property<string>("Region")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("region");

                    b.Property<char?>("RegionCode")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("region_code");

                    b.HasKey("Id")
                        .HasName("dno_pkey");

                    b.ToTable("dno", (string)null);
                });

            modelBuilder.Entity("EnergyUtilityApi.DnoNeedRegion", b =>
                {
                    b.Property<int>("DnoId")
                        .HasColumnType("integer")
                        .HasColumnName("dno_id");

                    b.Property<int>("NeedRegionSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("need_region_source_id");

                    b.HasIndex("DnoId");

                    b.ToTable("dno_need_regions", (string)null);
                });

            modelBuilder.Entity("EnergyUtilityApi.DnoPriceCapRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnnualStandingCharge")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("annual_standing_charge");

                    b.Property<int?>("DnoId")
                        .HasColumnType("integer")
                        .HasColumnName("dno_id");

                    b.Property<string>("MeterType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meter_type");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<decimal?>("UnitRatePence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("unit_rate_pence");

                    b.HasKey("Id")
                        .HasName("regional_price_cap_rates_pkey");

                    b.ToTable("dno_price_cap_rates", (string)null);
                });

            modelBuilder.Entity("EnergyUtilityApi.ElecConsPostcode", b =>
                {
                    b.Property<string>("Postcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode");

                    b.Property<decimal?>("MeanCons")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("mean_cons");

                    b.Property<decimal?>("MedianCons")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("median_cons");

                    b.Property<int?>("NumMeters")
                        .HasColumnType("integer")
                        .HasColumnName("num_meters");

                    b.HasKey("Postcode")
                        .HasName("postcode_cons_pkey");

                    b.HasIndex(new[] { "Postcode" }, "idx_postcode_lookup");

                    b.ToTable("elec_cons_postcodes", (string)null);
                });

            modelBuilder.Entity("EnergyUtilityApi.RegionalWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("Multiplier")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("multiplier");

                    b.Property<string>("Region")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("region");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<string>("Value")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("value");

                    b.Property<int?>("ValueId")
                        .HasColumnType("integer")
                        .HasColumnName("value_id");

                    b.HasKey("Id")
                        .HasName("regional_weights_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("regional_weights", (string)null);
                });

            modelBuilder.Entity("EnergyUtilityApi.WeightCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("weight_categories_pkey");

                    b.ToTable("weight_categories", (string)null);
                });

            modelBuilder.Entity("EnergyUtilityApi.DnoNeedRegion", b =>
                {
                    b.HasOne("EnergyUtilityApi.Dno", "Dno")
                        .WithMany()
                        .HasForeignKey("DnoId")
                        .IsRequired()
                        .HasConstraintName("dno_fk");

                    b.Navigation("Dno");
                });

            modelBuilder.Entity("EnergyUtilityApi.RegionalWeight", b =>
                {
                    b.HasOne("EnergyUtilityApi.WeightCategory", "Category")
                        .WithMany("RegionalWeights")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("category_fk");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EnergyUtilityApi.WeightCategory", b =>
                {
                    b.Navigation("RegionalWeights");
                });
#pragma warning restore 612, 618
        }
    }
}
